#pragma once
#include <string>
//#include <bitset>


enum class MsgType {
    NONE = 0,
	WELCOME,
	HOST_INFO,
	SERVER_CREATION,
	SERVER_INFO,
	JOIN,
	USER_LIMIT_CHANGED,
	RPL_NICK_CHANGE = 353,
	NICKNAME_IN_USE = 433,
	NOT_OPERATOR = 482,     // ERR_CHANOPRIVSNEEDED,
	RPL_TOPIC = 332,
	CLIENT_QUIT,
	PASSWORD_APPLIED,
	INVALID_INVITE,
	INVALID_CHANNEL_NAME =  479, 
	CHANNEL_MODE_CHANGED,
	CLIENT_MODE_CHANGED,
	INVITE_ONLY = 473,
	INVALID_PASSWORD = 475,
	NEED_MORE_PARAMS =  461, // ERR_NEEDMOREPARAMS,
	NO_SUCH_CHANNEL = 403,  // ERR_NOSUCHCHANNEL,
    ERR_USERNOTINCHANNEL = 441, // Often used for INVITE/KICK targets
    // ERR_NOTONCHANNEL = 442,     // for PART
    ERR_USERONCHANNEL = 443,    // Often used for INVITE/KICK targets
	INVALID_TARGET  = 502,   // ERR_USERSDONTMATCH (commonly used for this scenario),
	NO_SUCH_NICK = 401,     // ERR_NOSUCHNICK
	NOT_ON_CHANNEL = 442,
	UNKNOWN_MODE  = 472,     // ERR_UNKNOWNMODE

	 // Successful replies for mode listing
    RPL_CHANNELMODEIS = 324, // Channel modes list
    RPL_UMODEIS = 221        // User mode list
};