#pragma once
#include <string>
//#include <bitset>


enum class MsgType {
    NONE = 0,
	WELCOME,
	HOST_INFO,
	SERVER_CREATION,
	SERVER_INFO,
	RPL_NICK_CHANGE = 353,
	NICKNAME_IN_USE = 433,
	NOT_OPERATOR = 482,     // ERR_CHANOPRIVSNEEDED,
	RPL_TOPIC = 332,
	CLIENT_QUIT,
	INVALID_PASSWORD,
	PASSWORD_APPLIED,
	INVALID_INVITE,
	CHANNEL_MODE_CHANGED,
	CLIENT_MODE_CHANGED,
	USER_LIMIT_CHANGED,
	NEED_MORE_PARAMS =  461, // ERR_NEEDMOREPARAMS,
	NO_SUCH_CHANNEL = 403,  // ERR_NOSUCHCHANNEL,
	NOT_IN_CHANNEL  = 442,   // ERR_NOTONCHANNEL,
	INVALID_TARGET  = 502,   // ERR_USERSDONTMATCH (commonly used for this scenario),
	NO_SUCH_NICK = 401,     // ERR_NOSUCHNICK
	UNKNOWN_MODE  = 472,     // ERR_UNKNOWNMODE

	 // Successful replies for mode listing
    RPL_CHANNELMODEIS = 324, // Channel modes list
    RPL_UMODEIS = 221        // User mode list
};