#pragma once
#include <string>
//#include <bitset>


enum class MsgType {
    NONE = 0,
	WELCOME,
	HOST_INFO,
	SERVER_CREATION,
	SERVER_INFO,
	JOIN,
	USER_LIMIT_CHANGED,
	UPDATE_CHAN, 
	PART,
	KICK,
	RPL_UMODEIS = 221,        // User mode list
    RPL_CHANNELMODEIS = 324, // Channel modes list
	RPL_TOPIC = 332,
	RPL_NICK_CHANGE = 353,
	CLIENT_QUIT,
	PASSWORD_APPLIED,
	INVALID_INVITE,
	INVALID_CHANNEL_NAME =  479, 
	CHANNEL_MODE_CHANGED,
	CLIENT_MODE_CHANGED,
	ERR_NOSUCHNICK = 401,     // ERR_NOSUCHNICK
	NO_SUCH_CHANNEL = 403,  // ERR_NOSUCHCHANNEL,
	NICKNAME_IN_USE = 433,
    ERR_USERNOTINCHANNEL = 441, // Often used for INVITE/KICK targets
    ERR_NOTONCHANNEL = 442,
	NOT_ON_CHANNEL = 442,
    ERR_USERONCHANNEL = 443,    // Often used for INVITE/KICK targets
	NEED_MORE_PARAMS =  461, // ERR_NEEDMOREPARAMS,
	CHANNEL_FULL = 471,
	UNKNOWN_MODE  = 472,     // ERR_UNKNOWNMODE
	INVITE_ONLY = 473,
	INVALID_PASSWORD = 475,
	NOT_OPERATOR = 482,     // ERR_CHANOPRIVSNEEDED,
	INVALID_TARGET  = 502   // ERR_USERSDONTMATCH (commonly used for this scenario),

};